services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph
    restart: always
    volumes:
      - rdf-data:/data
    command: --location /data serve --bind 0.0.0.0:7878
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
        mode: host
  pg:
    build:
      context: ./docker/pg
    restart: always
    env_file:
    - postgres.env
    volumes:
      - db-data:/home/postgres/pgdata/data
    healthcheck:
      test: ["CMD", "pg_isready", "-u", "postgres", "-d", "brick"] # TODO: load from env?
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  frontend:
    restart: always
    environment:
      MODEL_NAMESPACE: "urn:ex/"
    depends_on:
      - oxigraph
      - pg
    build:
      context: ./frontend
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host

volumes:
  db-data:
  rdf-data:
